/* ============================================================
   Student Insight — Service Worker v11.0
   Caches the app shell for offline use.
   Cache is versioned — bump CACHE_VERSION on each deploy.

   v11.0 (bug #4 fix): SHELL_ASSETS are now built from the service
   worker's own runtime scope (self.registration.scope) instead of
   hardcoded absolute paths starting with "/". A hardcoded "/" always
   resolves to the ORIGIN root — correct for studin.in (prod, served
   at the domain root) but silently wrong for the QA GitHub Pages
   deployment (served under /student-insight/), where it pointed at
   paths that don't exist. self.registration.scope is computed by the
   browser at registration time from wherever sw.js actually lives, so
   this now auto-detects prod / QA / local / any future subpath with
   no hostname or path string-matching needed anywhere in this file.
============================================================ */

const CACHE_VERSION = 'sia-v12.28';
const CACHE_NAME    = CACHE_VERSION;

// e.g. "https://studin.in/" on prod, or
// "https://sandeephakki-qa.github.io/student-insight/" on QA — whatever
// directory this file was actually registered from.
const SCOPE = self.registration.scope;

// App shell assets to cache on install
// BEGIN SHELL_ASSETS (generated by scripts/gen-sw-precache.py — do not edit)
const SHELL_ASSETS = [
  SCOPE + 'index.html',
  SCOPE + 'manifest.json',
  SCOPE + 'img/logo.png',
  SCOPE + 'img/author.png',
  SCOPE + 'img/favicon.png',
  SCOPE + 'img/icon-192.png',
  SCOPE + 'img/icon-512.png',
  SCOPE + 'css/core.css',
  SCOPE + 'css/onboarding-slider.css',
  SCOPE + 'css/video-tiles.css',
  SCOPE + 'css/vs-shell.css',
  SCOPE + 'bal/common/bucket-rules.js',
  SCOPE + 'bal/common/compute-continuity.js',
  SCOPE + 'bal/common/compute-derived.js',
  SCOPE + 'bal/common/compute-stats.js',
  SCOPE + 'bal/common/mark-parse.js',
  SCOPE + 'bal/compare/compute-compare.js',
  SCOPE + 'bal/export/export-pdf.js',
  SCOPE + 'bal/scholarship/scholarship-completeness-grid.js',
  SCOPE + 'bal/scholarship/scholarship-eligibility-engine.js',
  SCOPE + 'bal/scholarship/scholarship-export.js',
  SCOPE + 'bal/scholarship/scholarship-report-views.js',
  SCOPE + 'bal/smart-plan/eligibility.js',
  SCOPE + 'bal/smart-plan/prompt-builder.js',
  SCOPE + 'bal/smart-plan/response-parser.js',
  SCOPE + 'bal/smart-plan/study-plan-pdf.js',
  SCOPE + 'bal/smart-search/smart-engine.js',
  SCOPE + 'bal/smart-search/smart-query-v2.js',
  SCOPE + 'core/analytics-loader.js',
  SCOPE + 'core/app-state.js',
  SCOPE + 'core/app-utils-init.js',
  SCOPE + 'core/async-utils.js',
  SCOPE + 'core/country-language-loader.js',
  SCOPE + 'core/debug-log.js',
  SCOPE + 'core/dom-helpers.js',
  SCOPE + 'core/dom-shim.js',
  SCOPE + 'core/env-config.js',
  SCOPE + 'core/feature-registry.js',
  SCOPE + 'core/main.js',
  SCOPE + 'core/onboarding-slider.js',
  SCOPE + 'core/ports.js',
  SCOPE + 'core/project-setup.js',
  SCOPE + 'core/read-feature-flags.js',
  SCOPE + 'core/render-i18n.js',
  SCOPE + 'core/setup-wizard.js',
  SCOPE + 'core/shared-constants.js',
  SCOPE + 'core/state-nav.js',
  SCOPE + 'core/studinpro-items.js',
  SCOPE + 'core/template-upload.js',
  SCOPE + 'core/theme-init.js',
  SCOPE + 'core/video-modal.js',
  SCOPE + 'core/vs-shell.js',
  SCOPE + 'dal/common/data-access.js',
  SCOPE + 'ui/common/continuity-dashboard.js',
  SCOPE + 'ui/common/feature-locked-modal.js',
  SCOPE + 'ui/common/inline-actions.js',
  SCOPE + 'ui/common/pitch-deck.js',
  SCOPE + 'ui/common/render-buckets.js',
  SCOPE + 'ui/common/render-core.js',
  SCOPE + 'ui/common/render-findings.js',
  SCOPE + 'ui/common/run-analysis.js',
  SCOPE + 'ui/common/studinpro-ticker.js',
  SCOPE + 'ui/compare/compare-ui.js',
  SCOPE + 'ui/export/export-ui.js',
  SCOPE + 'ui/scholarship/scholarship-audit-detail.js',
  SCOPE + 'ui/scholarship/scholarship-dashboard.js',
  SCOPE + 'ui/scholarship/scholarship-edit-grid.js',
  SCOPE + 'ui/scholarship/scholarship-export-ui.js',
  SCOPE + 'ui/scholarship/scholarship-nav.js',
  SCOPE + 'ui/smart-plan/smart-plan-nav.js',
  SCOPE + 'ui/smart-plan/smart-plan-render.js',
  SCOPE + 'i18n/about/en.json',
  SCOPE + 'i18n/ai/en.json',
  SCOPE + 'i18n/common/en.json',
  SCOPE + 'i18n/compare/en.json',
  SCOPE + 'i18n/faq/en.json',
  SCOPE + 'i18n/onboarding/en.json',
  SCOPE + 'i18n/pdf/en.json',
  SCOPE + 'i18n/scholarship/en.json',
  SCOPE + 'i18n/setup/en.json',
  SCOPE + 'i18n/shell/en.json',
  SCOPE + 'i18n/smart-plan/en.json',
  SCOPE + 'i18n/smart-search/en.json',
  SCOPE + 'i18n/studinpro/en.json',
  SCOPE + 'i18n/validation/en.json',
];
// END SHELL_ASSETS

// BEGIN PRECACHE_CDN (generated by scripts/gen-sw-precache.py — do not edit)
const PRECACHE_CDN = [
  'https://cdn.jsdelivr.net/npm/xlsx-js-style@1.2.0/dist/xlsx.bundle.js',
  'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js',
  'https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.4/gsap.min.js',
  'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js',
  'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js',
];
// END PRECACHE_CDN

// CDN assets the app depends on (cache on first fetch)
// Kept in sync with the CDN <script> tags in index.html:
// jQuery 3.7.1, SheetJS (xlsx) 0.18.5, jsPDF 2.5.1, JSZip 3.10.1,
// Chart.js 4.4.1, Google Fonts (Inter, DM Sans)
const CDN_ORIGINS = [
  'https://cdnjs.cloudflare.com',
  'https://cdn.jsdelivr.net',
  'https://fonts.googleapis.com',
  'https://fonts.gstatic.com',
];

/* ── Install: pre-cache app shell ── */
self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => {
      // Add each asset on its own (allSettled): cache.addAll() is all-or-nothing, so a
      // single 404 used to leave the cache empty and offline broken on first load.
      const urls = SHELL_ASSETS.concat(PRECACHE_CDN);
      return Promise.allSettled(urls.map(u => cache.add(u))).then(rs => {
        const failed = rs.map((r, i) => r.status === 'rejected' ? urls[i] : null).filter(Boolean);
        if (failed.length) console.warn('[SW] Not precached (will cache on first fetch):', failed);
      });
    }).then(() => self.skipWaiting())
  );
});

/* ── Activate: clean up old caches ── */
// FIX (review #9): CACHE_VERSION above is still a hand-typed string —
// switching that to a build/content hash needs a build step this static-file
// project intentionally doesn't have, so left as a manual bump for now (just
// remember to bump it every deploy, or updates silently won't reach users).
// After cleanup, claim clients so the page-side `controllerchange` listener
// (see core/app-utils-init.js) fires a "new version available" toast instead
// of the update sitting silently until next full close+reopen.
self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys
          .filter(k => k !== CACHE_NAME)
          .map(k => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
});

/* ── Fetch: network-first for app shell, cache-first for CDN ── */
self.addEventListener('fetch', event => {
  // Never intercept chrome-extension or non-http
  if (!event.request.url.startsWith('http')) return;

  // CDN assets — cache first, fallback to network
  const isCDN = CDN_ORIGINS.some(o => event.request.url.startsWith(o));
  if (isCDN) {
    event.respondWith(
      caches.match(event.request).then(cached => {
        if (cached) return cached;
        return fetch(event.request).then(response => {
          if (response && response.status === 200) {
            const clone = response.clone();
            caches.open(CACHE_NAME).then(c => c.put(event.request, clone));
          }
          return response;
        });
      })
    );
    return;
  }

  // Sample .xlsx files (samples/*.xlsx on any environment) — always go to
  // network. Never served stale from cache: a stale cached "Try Now" file
  // would silently show a QA tester (or a real user) outdated demo data
  // with no indication it's not the current file.
  if (/\.xlsx($|\?)/i.test(event.request.url)) {
    event.respondWith(fetch(event.request));
    return;
  }

  // App shell — network first, fallback to cache
  // (This is a stateless, in-browser-only app — no student data ever
  // touches the network or this cache; see index.html's Project
  // Intelligence Block §1 for the privacy model this mirrors.)
  // v4.29 SW fix: this used to run for EVERY non-CDN/non-xlsx request,
  // including unrelated cross-origin requests (e.g. a dev-server-injected
  // analytics beacon) that this app never asked for and has no cached
  // entry for. When those got CORS-blocked, the .catch() fallback called
  // caches.match(), got `undefined` back, and respondWith(undefined)
  // throws "Failed to convert value to 'Response'" — a real, repeating
  // console error, not just noise. Scope this handler to same-origin
  // requests only (everything this app shell actually owns); anything
  // else is left completely unintercepted, exactly as if this SW didn't
  // exist for it.
  if (!event.request.url.startsWith(self.location.origin)) return;

  event.respondWith(
    fetch(event.request)
      .then(response => {
        if (response && response.status === 200) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then(c => c.put(event.request, clone));
        }
        return response;
      })
      .catch(() =>
        caches.match(event.request).then(cached => cached || Response.error())
      )
  );
});
