#!/usr/bin/env python3
"""Regenerates (or --check verifies) the precache lists inside sw.js so the whole
app shell (index, CSS, every JS module, English i18n shards, icons, pinned CDN
scripts) is cached at install and works offline from the FIRST visit.
  python3 scripts/gen-sw-precache.py          # rewrite sw.js lists
  python3 scripts/gen-sw-precache.py --check  # exit 1 if sw.js is out of date
Other-language i18n shards are fetched + cached on first use (runtime cache)."""
import os, re, sys, glob
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__))); os.chdir(root)
files = ['index.html', 'manifest.json', 'img/logo.png', 'img/author.png', 'img/favicon.png', 'img/icon-192.png', 'img/icon-512.png']
files += sorted(glob.glob('css/*.css'))
files += sorted(f for d in ('core', 'ui', 'bal', 'dal') for f in glob.glob(d + '/**/*.js', recursive=True))
files += sorted(glob.glob('i18n/en.json') + glob.glob('i18n/*/en.json'))
files = [f.replace(os.sep, '/') for f in files if os.path.exists(f)]
html = open('index.html', encoding='utf-8', errors='replace').read()
cdn = sorted(set(re.findall(r'<script[^>]+src="(https://[^"]+)"', html)))
sw = open('sw.js', encoding='utf-8', errors='surrogateescape').read()
def block(name, items, fmt):
    return '// BEGIN %s (generated by scripts/gen-sw-precache.py — do not edit)\nconst %s = [\n%s\n];\n// END %s' % (name, name, '\n'.join('  ' + fmt(i) + ',' for i in items), name)
new_shell = block('SHELL_ASSETS', files, lambda f: "SCOPE + '%s'" % f)
new_cdn = block('PRECACHE_CDN', cdn, lambda u: "'%s'" % u)
def swap(s, name, blk):
    pat = re.compile(r'// BEGIN %s .*?// END %s' % (name, name), re.S)
    return pat.sub(lambda m: blk, s) if pat.search(s) else None
out = sw
if 'BEGIN SHELL_ASSETS' not in out:
    out = re.sub(r'const SHELL_ASSETS = \[.*?\];', lambda m: new_shell + '\n\n' + new_cdn, out, count=1, flags=re.S)
else:
    out = swap(out, 'SHELL_ASSETS', new_shell); out = swap(out, 'PRECACHE_CDN', new_cdn)
if '--check' in sys.argv:
    if out != sw: print('sw.js precache list is stale — run: python3 scripts/gen-sw-precache.py'); sys.exit(1)
    print('sw.js precache up to date (%d shell files, %d CDN scripts)' % (len(files), len(cdn))); sys.exit(0)
open('sw.js', 'w', encoding='utf-8', errors='surrogateescape').write(out)
print('sw.js updated: %d shell files, %d CDN scripts' % (len(files), len(cdn)))
