#!/usr/bin/env python3
"""
Regenerates the SR_STRINGS_EN object literal in core/render-i18n.js from
the 11 i18n/<feature>/en.json shards (merged in the same order the app
itself merges them at runtime), so the two can never silently drift
apart again.

Why this exists (review #7 / setup-page-raw-keys bug):
SR_STRINGS_EN is the EMERGENCY, always-present English fallback baked
directly into js/render-i18n.js — it's what the app uses for the very
first synchronous render before i18n/en.json has finished fetching, and
what it falls back to permanently if that fetch fails (including the
file:// use case documented in About §2, where fetch() of sibling files
is blocked by the browser entirely). It used to be a HAND-MAINTAINED
subset (~330 of en.json's 1174 keys) that quietly fell further behind
every time someone added a new srT() call without also editing this
block by hand. Symptom: raw key names like "val_mode_institution"
rendering on screen instead of real text, on the Setup page and
elsewhere, for however long survived that gap between "added the key
to en.json" and "remembered to also add it here."

Fix: SR_STRINGS_EN is no longer hand-maintained at all. It's a full,
mechanical 1:1 mirror of every key across the 11 i18n/<feature>/en.json
shards, regenerated by this script. Run this any time any of those
en.json files change:

    python3 scripts/sync-sr-strings-en.py

It rewrites the SR_STRINGS_EN block in place between the
"const SR_STRINGS_EN={" and its matching "};" and leaves the rest of
js/render-i18n.js untouched. Keys starting with "_" (e.g. "_meta") are
skipped — those are metadata for the JSON files, not translatable
strings, and were never part of SR_STRINGS_EN.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET_JS = ROOT / "core" / "render-i18n.js"

# Must mirror I18N_FEATURES in core/render-i18n.js exactly (order matters —
# later shards override earlier on key collision, same as the browser's own
# loadSplitOrLegacyLanguage()/Object.assign merge). "onboarding" is
# deliberately excluded — it's a separate i18n namespace fetched directly by
# onboarding-slider.js, never merged into I18N_TABLES/SR_STRINGS_EN.
I18N_FEATURES = ["common", "smart-search", "compare", "scholarship", "about",
                  "faq", "setup", "validation", "pdf", "ai", "shell"]

# Matches a bare JS identifier that's safe to leave unquoted as an object
# key (matches how the original hand-written SR_STRINGS_EN was styled).
_BARE_KEY_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def js_key(key: str) -> str:
    if _BARE_KEY_RE.match(key):
        return key
    return json.dumps(key, ensure_ascii=False)


def js_string(value: str) -> str:
    # json.dumps gives us correct escaping (quotes, backslashes, newlines,
    # unicode) and keeps non-ASCII characters literal (ensure_ascii=False)
    # so the file stays readable, matching the existing hand-written style.
    return json.dumps(value, ensure_ascii=False)


def load_merged_en():
    merged = {}
    for feature in I18N_FEATURES:
        path = ROOT / "i18n" / feature / "en.json"
        if not path.exists():
            print(f"WARNING: shard missing, skipped: {path.relative_to(ROOT)}", file=sys.stderr)
            continue
        with path.open(encoding="utf-8") as f:
            shard = json.load(f, object_pairs_hook=dict)
        merged.update(shard)  # later shards override earlier, matches Object.assign order in loadSplitOrLegacyLanguage()
    return merged


def main():
    en = load_merged_en()

    lines = []
    for key, value in en.items():
        if key.startswith("_"):
            continue
        if not isinstance(value, str):
            print(f"WARNING: skipping non-string value for key {key!r}: {value!r}", file=sys.stderr)
            continue
        lines.append(f"  {js_key(key)}:{js_string(value)},")

    new_block = "const SR_STRINGS_EN={\n" + "\n".join(lines) + "\n};"

    content = TARGET_JS.read_text(encoding="utf-8")
    start = content.index("const SR_STRINGS_EN={")
    # find the matching closing "};" for this object literal by scanning
    # for the first "\n};" after start (SR_STRINGS_EN is a flat object of
    # string values only, so no nested braces to worry about).
    end_marker = "\n};"
    end = content.index(end_marker, start) + len(end_marker)

    old_block = content[start:end]
    if old_block == new_block:
        print("SR_STRINGS_EN already up to date with the i18n/*/en.json shards — no changes made.")
        return

    new_content = content[:start] + new_block + content[end:]
    TARGET_JS.write_text(new_content, encoding="utf-8")
    print(f"Regenerated SR_STRINGS_EN: {len(lines)} keys (merged from {len(I18N_FEATURES)} i18n/*/en.json shards).")
    print(f"Wrote {TARGET_JS.relative_to(ROOT)}.")


if __name__ == "__main__":
    main()
